### ISSUE TITLE
Important: CSS code formatting and structure.

### ISSUE THREAD

**Issue by josephtkim** [dbuchnat/prj-rev-bwfs-dasmoto#7]
For CSS code, you always want to apply all the properties inside the single selector, and not individually at a time. In addition, each property should be on a new line. Here is how it should look,

```css
body {
  font-family: Helvetica;
}

h1 {
  font-size: 100px;
  font-weight: bold;
  color: khaki;
  text-align: center;
  background-image: url("/Users/dbuchnat/Documents/projects/arts/resources/media/pattern.jpeg");
}

h2 { 
  font-size: 32px;
  font-weight: bold;
  color: white;
}

.brush {
  background-color: mediumspringgreen;
}

.frame {
  background-color: lightcoral;
}

.paint {
  background-color: skyblue;
}

section {
  color: blue;
  margin: 10;
  padding: 0px;
}
```
